Repository parallel-runtimes/lomp, pull requests merged in 2021-07, with the labels that each got.

#16 Fix a few errors in README.md
  README.md
Labels: documentation

#17 Fix README.md
  README.md
Labels: bug, documentation

#18 Bugfix: libnuma was failing on RISC-V
  src/numa_support.cc
Labels: bug

#15 WIP: Timer enhancements and better architecture detection.
  microBM/BMutils.py
  microBM/CMakeLists.txt
  microBM/channel.h
  microBM/generateRandomAccess.py
  microBM/loadsStores.cc
  microBM/nominalFrequency.cc
  microBM/runLS.py
  microBM/variadic.cc
  scripts/plot.py
  scripts/toCSV.py
  src/entrypoints.cc
  src/stats-timing.cc
  src/target_arm.h
  tests/test_taskargs.c
Labels: enhancement

#20 Update build documentation with -DLOMP_ARM64_ARCHITECTURE
  README.md
Labels: documentation
